### ISSUE TITLE
Error in health check if handler does not exist.

### ISSUE THREAD

**Issue by AbhilakshSinghReen** [DERaC-IO/DeracioTSS#6]
### **Steps to reproduce**
1. Make a fresh clone of the repository and run tss.py.
2. On the main menu run the health check without creating any handlers.

### **Error Trace**
Traceback (most recent call last):
  File "D:\Programming\Job\DERaC\d5\DeracioTSS\tss.py", line 923, in <module>
    __main__()
  File "D:\Programming\Job\DERaC\d5\DeracioTSS\tss.py", line 883, in __main__
    tss.health()
  File "D:\Programming\Job\DERaC\d5\DeracioTSS\tss.py", line 776, in health
    status, message = self.loadHandlers()
  File "D:\Programming\Job\DERaC\d5\DeracioTSS\tss.py", line 745, in loadHandlers
    return status, message
UnboundLocalError: local variable 'status' referenced before assignment

### **Expected Behavior**
A message should be displayed saying handler does not exist.

**Comment by ts0924** [comment]
Thanks, I did the same and found your pull request!

**Comment by AbhilakshSinghReen** [comment]
Alright, I am closing this issue.

**Comment by AbhilakshSinghReen** [comment]
Alright, I am closing this issue.
